config/routes.rb
Rails.application.routes.draw do
  #Location Pages
  resources :locations do
    resources:comments, only: [:create]
  end
  resources:likes, only: [:create, :destroy]
  
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
 #HomePage
 root 'pages#home'
 #MapPage
 get 'map', to: 'pages#map'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :location
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
  has_many :likes, as: :likeable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    #Create post for the current user
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_massages.to_sentence
    end
      redirect_to location_path(params[:location_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_id).merge(location_id: params[:location_id])
  end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!--User name & Time-->
<div class="container" id="comments_font">
  <% if comment.user.name.nil? %>
    <small><%= comment.user.email %></small> |
  <% else %>
    <small><%= comment.user.name %></small> |
  <% end %>
  <small><%= "#{time_ago_in_words(comment.created_at)}" %> <i class="bi bi-clock"></i></small>
  <div>
  <!--Comment Content-->
  <div class="comment_text">
    <%= comment.content %></div>
    <!--Like Button-->
    <div>
    <%= render partial: 'likes/button', locals: { likeable: comment } %>
    <!--Reply-->
    <a href="#" class="comment_form_display">Reply <i class="bi bi-chat-left"></i></a>
    <div class="comment_form">
     <%= render partial: 'comments/form', locals: {location: comment.location, parent: comment } %>
    </div>
    </div>
    <hr/>
    <br/>
     <!--Sub-Comment-->
    <div class="sub_comment">
      <%= render comment.comments.order(id: :desc) %> 
    </div>
  </div>  
 </div>

<script>
  document.querySelectorAll('.comment_form_display').forEach((el) => {
    el.addEventListener('click', (ev) => {
      ev.preventDefault();
      el.nextElementSibling.style = 'display: block;'
    })
  })
 </script>

app/views/comments/_f.html.erb
<%= form_with(model: [location, location.comments.build]) do |f| %>
  <div class="form-control">
    <%= f.rich_text_area :body %>
  </div>

<div id="what">
WHAT
</div>

  <div class="form-control">
    <%= f.submit "Reply", class: "btn btn-primary mt-1" %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<form  action="<%= location_comments_path(location) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if !parent.nil? %>
    <input type="hidden" name="comment[parent_id]" value="<%= parent.id %>">
  <% end %>
  <!--Text Area-->
  <div class="container">
    <div class="comment_reply_cont">
    <textarea name="comment[content]"class="comment_reply_text"></textarea>
    </div>
    <!--Submit Button-->
      <div class="comment_reply_submit_cont">
        <input type="submit" value="Submit" class="comment_reply_submit">
      </div>
    </div>
</form>