config/routes.rb
Rails.application.routes.draw do
  #Location Pages
  resources :locations do
    resources:comments, only: [:create]
  end
  resources:likes, only: [:create, :destroy]
  
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
 #HomePage
 root 'pages#home'
 #MapPage
 get 'map', to: 'pages#map'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @like = current_user.likes.new(like_params)

    if !@like.save
      flash[:notice] = @like.errors.full_messages.to_sentence
    end
      redirect_back(fallback_location: locations_url)
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    likeable = @like.likeable
    @like.destroy 
    redirect_back(fallback_location: locations_url)
  end

  private 

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_button.html.erb
<% if current_user %>
<div class="row">
 <div class="col">
  <!--Like/Unlike Buttons-->
  <!--Like Button for Location -->
<% like = current_user.likes.find_by(likeable: likeable)%>
  <% if like.nil? %>
  <form action="/likes" method="post" class="form_comment_like">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="like[likeable_id]" value="<%= likeable.id %>">
    <input type="hidden" name="like[likeable_type]" value="<%= likeable.class.to_s %>">
    <input type="submit" value="Like" class="like_unlike_button">
    <i class="bi bi-heart-fill" id="like_heart"></i>
    <!--Amount of Likes-->
    <%= likeable.likes.count %>
  </form>
<% else %>
  <form action="<%= like_path(like) %>" method="post" class="form_comment_like">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Unlike" class="like_unlike_button">
    <i class="bi bi-heart-fill" id="like_heart"></i>
    <!--Amount of Likes-->
    <%= likeable.likes.count %>
  </form>
<% end %>

<% else %>
<h6>Sign in to use the Comment Section</h6>
<% end %>    
 </div>
</div>